name: CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      - name: Install dependencies and run tasks
        run: |
          gem install bundler
          NBR_RUNNING_CONTAINERS=$(docker ps | wc -l)
          bundle install --jobs 4 --retry 3
          bundle exec rake docker:run
          # Sleep for a while to let the container start
          sleep 120
          # Check that the number of running containers has increased
          if (( $(docker ps | wc -l) > NBR_RUNNING_CONTAINERS )); then
            echo "At least one new container is running"
            bundle exec rake docker:rmi
          else
            echo "No new container is running"
            exit 1
          fi